
[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#00CA00"

# Background color for the main content area.
backgroundColor = "#16242E"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#202E36"

# Color used for almost all text.
textColor = "#E1E5E6"

# The font family for all text in the app, except code blocks. One of
# "sans serif", "serif", or "monospace".
# To use a custom font, it needs to be added via [theme.fontFaces]. 🐰🥚
font = "sans serif"